from typing import Any
from langgraph.graph import END, StateGraph
from backend.app.agents.coder import CoderAgent
from backend.app.agents.debugger import DebuggerAgent
from backend.app.agents.planner import PlannerAgent
from backend.app.agents.reviewer import ReviewerAgent
from backend.app.agents.state import AgentState, MAX_DEBUG_ITERATIONS
from backend.app.core.config import settings
from backend.app.core.logging import logger
from mcp_servers.client import MCPClientManager
from rag.retrieval.vector_store import CodeRAGStore


class AgentOrchestrator:
    """LangGraph Multi-Agent Engine orchestrating end-to-end autonomous engineering workflow."""

    def __init__(self, workspace_root: str | None = None):
        self.workspace_root = workspace_root or settings.ALLOWED_HOST_WORKSPACE_ROOT
        self.mcp_client = MCPClientManager(self.workspace_root)
        self.rag_store = CodeRAGStore()

        self.planner = PlannerAgent(self.rag_store)
        self.coder = CoderAgent(self.mcp_client)
        self.debugger = DebuggerAgent(self.mcp_client)
        self.reviewer = ReviewerAgent()

        self.graph = self._build_graph()

    def _build_graph(self) -> Any:
        builder = StateGraph(AgentState)

        # Define Nodes
        builder.add_node("planner", self._plan_step)
        builder.add_node("coder", self._code_step)
        builder.add_node("test", self._test_step)
        builder.add_node("debugger", self._debug_step)
        builder.add_node("reviewer", self._review_step)
        builder.add_node("create_pr", self._create_pr_step)

        # Build Edges
        builder.set_entry_point("planner")
        builder.add_edge("planner", "coder")
        builder.add_edge("coder", "test")

        builder.add_conditional_edges(
            "test",
            self._check_test_outcome,
            {
                "pass": "reviewer",
                "debug": "debugger",
                "fail": END,
            },
        )
        builder.add_edge("debugger", "test")

        builder.add_conditional_edges(
            "reviewer",
            self._check_review_outcome,
            {
                "approved": "create_pr",
                "rejected": END,
            },
        )
        builder.add_edge("create_pr", END)

        return builder.compile()

    def _plan_step(self, state: AgentState) -> dict[str, Any]:
        return self.planner.run(state)

    def _code_step(self, state: AgentState) -> dict[str, Any]:
        return self.coder.run(state)

    def _test_step(self, state: AgentState) -> dict[str, Any]:
        logger.info("AgentOrchestrator invoking Execution MCP run_tests in sandbox...")
        exec_res = self.mcp_client.execute_tool("run_tests", {"test_path": "tests"})
        return {"execution_result": exec_res}

    def _debug_step(self, state: AgentState) -> dict[str, Any]:
        return self.debugger.run(state)

    def _review_step(self, state: AgentState) -> dict[str, Any]:
        return self.reviewer.run(state)

    def _create_pr_step(self, state: AgentState) -> dict[str, Any]:
        logger.info("AgentOrchestrator invoking GitHub MCP create_pull_request...")
        pr_result = self.mcp_client.execute_tool(
            "create_pull_request",
            {
                "title": state.get("task_title", "Automated Bug Fix"),
                "body": f"Automated fix generated by CodePilot-MCP.\n\nDescription: {state.get('task_description')}",
                "head_branch": state.get("feature_branch", "codepilot/fix-branch"),
                "base_branch": state.get("target_branch", "main"),
            },
        )
        return {"pr_result": pr_result, "status": "COMPLETED"}

    def _check_test_outcome(self, state: AgentState) -> str:
        exec_res = state.get("execution_result", {})
        exit_code = exec_res.get("exit_code", 1)
        tests_failed = exec_res.get("tests_failed", 0)

        if exit_code == 0 and tests_failed == 0:
            return "pass"

        iterations = state.get("debug_iterations", 0)
        if iterations < MAX_DEBUG_ITERATIONS:
            return "debug"
        return "fail"

    def _check_review_outcome(self, state: AgentState) -> str:
        review = state.get("review")
        if review and review.approved:
            return "approved"
        return "rejected"

    def run_task(self, initial_state: AgentState) -> AgentState:
        """Run complete workflow graph."""
        logger.info(f"Starting agent workflow for task '{initial_state.get('task_title')}'")
        final_state = self.graph.invoke(initial_state)
        return final_state
